---
groups:
  - name: node_exporter_alerts
    rules:
      - alert: NodeExporterDown
        expr: up{job="node_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down on {{ $labels.instance }}"
          description: "No metrics received from Node Exporter on {{ $labels.instance }}"

  - name: jenkins_alerts
    rules:
      - alert: JenkinsJobFailure
        expr: jenkins_job_last_build_duration_seconds{job="jenkins", result="FAILURE"} > 0
        for: 1m
        annotations:
          summary: "Jenkins job has failed!"
          description: "The job {{ $labels.job }} has failed. Check logs for details."