groups:
  - name: node_exporter_alerts
    rules:
      - alert: NodeExporterDown
        expr: up{job="node_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down on {{ $labels.instance }}"
          description: "No metrics received from Node Exporter on {{ $labels.instance }} for the last 1 minute."