global:
  resolve_timeout: 1m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url:
          'SLACK_WEBHOOK'
        channel: '#all-sre'
        send_resolved: true

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
