global:
  resolve_timeout: 5m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#all-sre'
        send_resolved: true

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
