version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
